-- 09/11
CREATE TABLE BOARD(
	BNO NUMBER(8) PRIMARY KEY,
	NAME VARCHAR2(20) NOT NULL,
	PASSWORD VARCHAR2(20) NOT NULL,
	TITLE VARCHAR2(20) NOT NULL,
	CONTENT VARCHAR2(20) NOT NULL,
	READCNT NUMBER(8) DEFAULT 0,
	REGDATE DATE DEFAULT SYSDATE
);
-- 시퀀스 생성 : SQL Error 권한이 불충분합니다
CREATE SEQUENCE board_seq;